//++++++++++++++++++++++++++++++++++++++
//++++INFO++++
(*

//Requirements:
Purpose: To play the burger shot game autonomously

Scenario: 
- Open BurgerShot
- Main Menu BurgerShot
- Instruction Menu BurgerShot
- Play BurgerShot
- Exit BurgerShot

//Github: 
https://github.com/r259c280/BurgerShot

*)
//++++++++++++++++++++++++++++++++++++++
//++++SET UP++++
set setupData to "Util/Json".initializeResourceData(JSONValue(file ResourcePath("SetupData.json")))
log "SetupData:" && setupData
set application to setupData.applicationRyan

set the remoteWorkInterval to setupData.remoteWorkInterval
set the scriptlogging to setupData.scriptlogging
set global waitTime to setupData.waitTime

try
	
	//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	//++++++++++++++++++Open Burger Shot++++++++++++++++++++
	set scenario to "Open Burger Shot"
	BeginTestCase scenario
	
	//++++++++++++++++++++++++++++++++++++++
	//++++ACTION++++ Open Eclipse and navigate to Burgershot game and open it
	run "Setup/Interaction".open application
	//run "Setup/Interaction".openAlt 
	log "Starting up BurgerShot"
	wait 10
	run "Setup/Interaction".startBurgerShot
	
	//++++++++++++++++++++++++++++++++++++++
	//++++VERIFICATION++++
	run "Util/Verify".saveScreenshot scenario
	
	EndTestCase scenario
	//+++++++++++++++++++Open BurgerShot+++++++++++++++++++++++++++++++
	//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	
	
	
	//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	//++++++++++++++++++Main Menu BurgerShot++++++++++++++++++++++++++++
	set scenario to "Main Frame"
	BeginTestCase scenario
	
	//++++++++++++++++++++++++++++++++++++++
	//++++VERIFICATION++++
	set rectangle to "Setup/Task".FrameSearchRectangle()
	wait 5
	log "Verifying the Mcdonalds Icon is visible in the top left corner"
	run "Util/Verify".imageIsVisible "Icon_Mcdonalds",rectangle
	run "Util/Verify".imageIsVisible "Banner_BurgerShot", rectangle
	
	log "Verifying Ronald Mcdonald is visible up in the middle of the menu"
	run "Util/Verify".imageIsVisible "MainFrame/Icon_RonMcdon",rectangle
	
	log "Verifying the 3 text icons are visible (Play, Instructions, and Exit)"
	run "Util/Verify".imageIsVisible "MainFrame/Text_Play",rectangle
	run "Util/Verify".imageIsVisible "MainFrame/Text_Instructions",rectangle
	run "Util/Verify".imageIsVisible "MainFrame/Text_Exit",rectangle
	
	run "Util/Verify".saveScreenshot scenario
	
	EndTestCase scenario
	//+++++++++++++++++++Main Menu BurgerShot+++++++++++++++++++++++++++
	//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	
	
	
	//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	//++++++++++++++++++Instruction Menu BurgerShot++++++++++++++++++++++++
	set scenario to "Instruction Frame"
	BeginTestCase scenario
	
	//++++++++++++++++++++++++++++++++++++++
	//++++ACTION++++ Open the Instruction Frame and validate the instructions
	set rectangle to "Setup/Task".FrameSearchRectangle()
	wait 3
	log "Navigating to instructions"
	click "MainFrame/Text_Instructions"
	
	//++++++++++++++++++++++++++++++++++++++
	//++++VERIFICATION++++
	log "Verifying Ronald Mcdonald is visible up in the middle of the menu"
	run "Util/Verify".imageIsVisible "Icon_Mcdonalds",rectangle
	run "Util/Verify".imageIsVisible "Banner_BurgerShot", rectangle
	run "Util/Verify".imageIsVisible "InstructionFrame/Text_InstructionInfo",rectangle
	run "Util/Verify".imageIsVisible "InstructionFrame/Text_EnterToContinue",rectangle
	
	run "Util/Verify".saveScreenshot scenario
	typeText returnKey
	wait 5
	run "Util/Verify".saveScreenshot scenario & " returned to menu frame"
	
	EndTestCase scenario
	//+++++++++++++++++++Main Menu BurgerShot+++++++++++++++++++++++++++
	//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	
	
	
	//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	//++++++++++++++++++Play BurgerShot++++++++++++++++++++++++++++++++
	set scenario to "Game Panel"
	BeginTestCase scenario
	
	//++++++++++++++++++++++++++++++++++++++
	//++++ACTION++++ Open the Game Panel and soak them burgers in KETCHUP!!!!
	click "MainFrame/Text_Play"
	Log "Finding the burger"
	run "Setup/Interaction".getThemBurgers
	
	//++++++++++++++++++++++++++++++++++++++
	//++++VERIFICATION++++
	run "Util/Verify".saveScreenshot scenario & "End Game"
	
	EndTestCase scenario
	//+++++++++++++++++++Play BurgerShot+++++++++++++++++++++++++++++++
	//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	
	
	
	//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	//++++++++++++++++++Exit BurgerShot++++++++++++++++++++++++++++++++
	set scenario to "Exit Game"
	BeginTestCase scenario
	
	//++++++++++++++++++++++++++++++++++++++
	//++++VERIFICATION++++
	wait 10
	run "Util/Verify".saveScreenshot scenario & "Results"
	
	//++++++++++++++++++++++++++++++++++++++
	//++++ACTION++++ If the game has been completed, exit the game
	run "Setup/Task".winOrLose
	log "exiting the game"
	click "MainFrame/Text_Exit"
	wait 3
	
	//++++++++++++++++++++++++++++++++++++++
	//++++VERIFICATION++++
	run "Util/Verify".saveScreenshot scenario && "End game returning to menu frame"
	
	EndTestCase scenario
	//+++++++++++++++++++Exit BurgerShot+++++++++++++++++++++++++++++++
	//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	
	catch exception
	LogError "Exception encountered" && exception.reason
	run "Util/Verify".saveScreenshot "Exception"
end try

//++++++++++++++++++++++++++++++++++++++
//++++++TEARDOWN+++++
typeText AltKey,F4
